name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-to-live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to live server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude="/public/uploads/"
          path: ./*
          remote_user: ${{secrets.USER}} 
          remote_host: ${{secrets.HOST}} 
          remote_port: ${{secrets.PORT}}
          remote_key : ${{secrets.SSH_PRIVATE_KEY}}
          remote_path: ${{secrets.PATH}}
      
          args: '-o ConnectTimeout=5'
          
      - name: run composer install
        run: composer install --no-dev --optimize-autoloader
      #- name: run php artisan migrate
      #run: php artisan migrate --force
      - name: run php artisan optimize clear
        run: php artisan optimize:clear
        
